### ISSUE TITLE
 calculate cell type-specificity

### ISSUE THREAD

**Issue by yipingLin** [andymckenzie/brain_gene_expression#1]
Sorry to bother you.
I read your published article entitled with “Brain Cell Type Specific Gene Expression and co-expression Network Architectures” and found the codes of calculating cell type-specificity of gene on your GitHub homepage. 
 
For darmanis data, there are functions of dfxp in dfxp.R and in clean_darmanis_dat.R. Could you please tell me which one you used? 
In addition, when building the grouping matrix in dfxp.R,
               design = model.matrix(~ fl + 0, barres_trimmed)
        colnames(design) = levels(fl) 
I don't know what fl is? Could you please help to figure me out?
 
Looking forward to your reply. 
Thank you.
 
 
Best regards,
Yiping Lin

**Comment by andymckenzie** [comment]
Hi Yiping, 

Thank you for reading our article! 

> For darmanis data, there are functions of dfxp in dfxp.R and in clean_darmanis_dat.R. Could you please tell me which one you used?

This GitHub repository was not referenced in the article because it is not associated with the article. The code in this repository was used in the creation of a separate shiny app that is not the same one as was presented in the article. It is also not the differential expression code that was used in the article. So, neither of them was used. I'm sorry for the confusion. 

This code was meant to be a record of the code for the separate shiny app but was never intended for anyone to use. I will write that on the repository README so that it is clear to others. 

> I don't know what fl is? Could you please help to figure me out?

fl refers to factor level. It is an arbitrary variable name sometimes used when creating a model matrix. In this code, it looks like it wasn't defined. I'm also sorry for the confusion about this.
